%Base de Conhecimento
%pais (portugal, espanha, italia, franca)
%tipo (cidade, campo, montanha, praia)
%estrelas (1,2,3,4,5)

if portugal and cidade and e1 then 1.
if portugal and cidade and e2 then 2.
if portugal and cidade and e3 then 3.
if portugal and cidade and e4 then 4.
if portugal and cidade and e5 then 5.
if espanha and cidade and e1 then 6.
if espanha and cidade and e2 then 7.
if espanha and cidade and e3 then 8.
if espanha and cidade and e4 then 9.
if espanha and cidade and e5 then 10.
if italia and cidade and e1 then 11.
if italia and cidade and e2 then 12.
if italia and cidade and e3 then 13.
if italia and cidade and e4 then 14.
if italia and cidade and e5 then 15.
if franca and cidade and e1 then 16.
if franca and cidade and e2 then 17.
if franca and cidade and e3 then 18.
if franca and cidade and e4 then 19.
if franca and cidade and e5 then 20.
if portugal and campo and e1 then 21.
if portugal and campo and e2 then 22.
if portugal and campo and e3 then 23.
if portugal and campo and e4 then 24.
if portugal and campo and e5 then 25.
if espanha and campo and e1 then 26.
if espanha and campo and e2 then 27.
if espanha and campo and e3 then 28.
if espanha and campo and e4 then 29.
if espanha and campo and e5 then 30.
if italia and campo and e1 then 31.
if italia and campo and e2 then 32.
if italia and campo and e3 then 33.
if italia and campo and e4 then 34.
if italia and campo and e5 then 35.
if franca and campo and e1 then 36.
if franca and campo and e2 then 37.
if franca and campo and e3 then 38.
if franca and campo and e4 then 39.
if franca and campo and e5 then 40.
if portugal and montanha and e1 then 41.
if portugal and montanha and e2 then 42.
if portugal and montanha and e3 then 43.
if portugal and montanha and e4 then 44.
if portugal and montanha and e5 then 45.
if espanha and montanha and e1 then 46.
if espanha and montanha and e2 then 47.
if espanha and montanha and e3 then 48.
if espanha and montanha and e4 then 49.
if espanha and montanha and e5 then 50.
if italia and montanha and e1 then 51.
if italia and montanha and e2 then 52.
if italia and montanha and e3 then 53.
if italia and montanha and e4 then 54.
if italia and montanha and e5 then 54.
if franca and montanha and e1 then 56.
if franca and montanha and e2 then 57.
if franca and montanha and e3 then 58.
if franca and montanha and e4 then 59.
if franca and montanha and e5 then 60.
if portugal and praia and e1 then 61.
if portugal and praia and e2 then 62.
if portugal and praia and e3 then 63.
if portugal and praia and e4 then 63.
if portugal and praia and e5 then 65.
if espanha and praia and e1 then 66.
if espanha and praia and e2 then 67.
if espanha and praia and e3 then 68.
if espanha and praia and e4 then 69.
if espanha and praia and e5 then 70.
if italia and praia and e1 then 71.
if italia and praia and e2 then 72.
if italia and praia and e3 then 73.
if italia and praia and e4 then 74.
if italia and praia and e5 then 75.
if franca and praia and e1 then 76.
if franca and praia and e2 then 77.
if franca and praia and e3 then 78.
if franca and praia and e4 then 79.
if franca and praia and e5 then 80.
